[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "da59a5e50efd2a07c1d4217f8889456e508e86d9"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "87a5c1940470a88a36c95c9e81a52d09f11bfd54f5537ea3081f2c8fb9bc5d52"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-x86_64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "68c27520c816ceec4ab9cd65688d8e1c195106c5"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "4816e63e9abdb22f96b02c94f0355354fa030427b711aeea6591109a18fd7a1e"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-i686-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "b2e9ab72efd5f3af73be9de612bdc367aff95a7b"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "9a84dad1653b4a01baafdea601acc246c54b28751e03b9dc3af32ccc7d35e988"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-aarch64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3b83b64d0e25a4e074fcce60c63de2d5e04ad78"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "47cfd75e2dc451d6dd3e1e02a07de6132ede2b5451364bed0ce7f39a5bc341ed"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-armv7l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "powerpc64le"
git-tree-sha1 = "369db753febf4f658544f1cf20311b24f12381b9"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "21b85e62a34a3574ba5e08060850d0e458071ffa1fa1a561735dafffb6a997c4"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-powerpc64le-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "dccc84fe6026e67ab03cf59f184237b1fa6c7e04"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "065ade2f7b4b27af53d6ba405e7682f440da2b056ce38ad35e30bc013b10de66"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-x86_64-linux-musl.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "3cfbbd3e07c07252f1a3fb83ccbab9d2b920bfb7"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "bc187d8a8ba43341a70384bc1aec13be8831df837560ec7c16f68fdb6179c628"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-i686-linux-musl.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "059b3a89b13f47f2f9d65d64076126bed7f10a9c"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "c2b25e07507024658078d23dba4f53ce2275c3402d8df9fc532f9fcc4566547f"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-aarch64-linux-musl.tar.gz"
[[LLVMCompilerRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3e387bebfcd9afe3d1809f46d72b24901fc9d07f"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "5bf0ed3065d3e53f8cd36cedb4e808c55dfbd6c53ec2a6a871bf723b8e027740"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-armv6l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e55d3fd83899e6aa4f51a5c861912fca2f1fa42b"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "b1b997d3fb5c91b0323f6a5f70535a786a0a25aed54c8213e65ea414a172020d"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-armv7l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "966b31080bd54350d5a2f39e4384b842c67e2959"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "2906a61a6a04261e1bb5344b133e3991d98c531017f0e32ba103d15a348af644"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-x86_64-w64-mingw32.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "93b2a4dad059fbfaa5e6ae497aae221dfecddc3d"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "9cfff42e1df686233c264a12134a95f2737111677ce4d48ded9b8fe21b3a00c1"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-v17.0.8-i686-w64-mingw32.tar.gz"

[[LLVMCompilerRT-build_log]]
arch = "x86_64"
git-tree-sha1 = "17ae45981cb7d02999f09fb5c7a4a8bbaf9de9b6"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "fa7936f65bf5319eea189dee7219e9c5ed6598a9608213af8f32315d0b036b74"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-x86_64-linux-gnu.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "i686"
git-tree-sha1 = "cd5c4d4c0ac49ae4d34718ef8b8c454d86f7b5d5"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "cb129f4d1ecc19fcf3cc18ea9ec3be95ceb0217dd233ad787e971c3bb6b4a95f"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-i686-linux-gnu.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "aarch64"
git-tree-sha1 = "31dfa73f0062b3236ff2b24fe9f8666145b6e0cc"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "c395dca3f5d47eafb92e5cf0c1587e38c84ec658fb23534df4457c8352840861"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-aarch64-linux-gnu.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50c18cde359417ab7030fe7461d1508904465664"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "c919abfd6293f696213f1b54108bb1e5100d3ea9fa81aaab5593c87150343cea"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-armv7l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "8d6c30b6d0623e80fe22ba85caa621e5efe3d389"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "b2661fa74a53f437ea17f4ec8c1775441d48f4e666155bf22916c8c2187e8ba4"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-powerpc64le-linux-gnu.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "x86_64"
git-tree-sha1 = "4db3795ee85457fcd945cb41745a3073bcf51717"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "74bb61cc758212c803a6c26df3a13278dc2f6abe4dfc9f16b318187c6556f477"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-x86_64-linux-musl.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "i686"
git-tree-sha1 = "24017a39327a9d40efe3627274200b4666ae0379"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "ce98f37e09c50915c1ee00d206703f45fab7ee6562f6444e22135b275d5c2939"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-i686-linux-musl.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "aarch64"
git-tree-sha1 = "4711fdace7dc99443e551156da05c7f97cc6983d"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "e984746c843dafb22e3729b2f3e9f18c7a13f6280baa298bf7fb7be68e8cc97c"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-aarch64-linux-musl.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aa83f1afeec615a50e44c17827d9f3c4ca8e9677"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "f2f97f2ce8dccbd19ead89245dccbbd976989661ca083bb730b9222d17fe0e96"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-armv6l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9431a610354f6b709a23b7a42475dc79416b943a"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "3fa8a5e09cb4a0f0628f7e6a50fbc2363578506e8b67ad1554b73e99ac58cfce"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-armv7l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "x86_64"
git-tree-sha1 = "24f0b0970730a7b1521ffea2c357d65ffb1f3f6a"
lazy = true
os = "windows"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "951158ee05db92fce66148e4080146d0dac3df4fac0535205a8b0f843eb8247a"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-x86_64-w64-mingw32.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "i686"
git-tree-sha1 = "f5e9a946e178977f290fecf8810e852d93b49894"
lazy = true
os = "windows"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "3cf0d03956a2d79f71d69fe4455f7cae667d6ed0e6a755c6f857013b2e29ec82"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-build_log-v17.0.8-i686-w64-mingw32.tar.gz"

[[LLVMCompilerRT-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e107919ae4e3d750194459f9a8bf5fefe71792d9"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "d76d15ee3829252a44a95f41bb880a72076f941fefb2366e531a26fad9caad5d"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-x86_64-linux-gnu.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "i686"
git-tree-sha1 = "45555790c15d396d05d39d3977a67945685f71ea"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "5467c86cde97a1cd890604fbe19d62daff2d828ef053d7efa171bc36c40280db"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-i686-linux-gnu.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "aarch64"
git-tree-sha1 = "5e895589e920d2339dfb181ea64e7337ac38a206"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "20cc0213a20fdb8a2d45c6c7440ed397f532437bfc49a1c7325a7244d114cca2"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-aarch64-linux-gnu.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "16c1fe3d1e3b2672de205b0d3f49342afce29d38"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "1b518b807bc295ee747ced1b45b981a1024073b4f9c20c18d5e91778b961e382"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-armv7l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "11b0cd504f5682d13f1c59897221818e0adf6cc6"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "3df04d6c083bb70765ab5e8b0f6c2809ebb2e87960ddd5602292fc5787f9888e"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-powerpc64le-linux-gnu.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "x86_64"
git-tree-sha1 = "3ea42de144b9741f58d276864878f38fd7357bcb"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "18de9b54abfe52f6b6ebef0512f65cc15f90b2d115dc95b950e4dfd2eb010ba9"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-x86_64-linux-musl.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "i686"
git-tree-sha1 = "c77d422904f0146251de285f8aa96689337aa064"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "125a58e06b7e408fe8f3c14e57496d904fbb331afadc0a337b62da90c0c0d282"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-i686-linux-musl.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "aarch64"
git-tree-sha1 = "801d54f6be79d995ad43f5206fd1b1c7ac22dffc"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "e04930296bfba626f2126c9ad7a6419512d7c3662f525f72d7a011906ba38095"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-aarch64-linux-musl.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3cf542ed16adb1a09dcec7adea04bead2d33b959"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "6b00a0901e62f188907cb1a607e1a7195e926d66479414cfb8e4749c9d914476"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-armv6l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa8c198434672e00dbb890a0b91cd39768f8c6cb"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "343233ff4f798d50a4f5680552e237194cf16b5dff78c4a9e38f86f6d540ff25"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-armv7l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "x86_64"
git-tree-sha1 = "dd4020d869784c3893546e5dbcb285096a5e27e6"
lazy = true
os = "windows"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "206fd8110595bde33e3f7c4accc5a61fce290d6781ab8089f3de856bd58901da"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-x86_64-w64-mingw32.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "i686"
git-tree-sha1 = "58ccf5fd24e3bd2e76929dda8c6ea578d024035f"
lazy = true
os = "windows"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "1fb2f5570fd644930d9c808cfde4fab78f17a01f821fabda00a562c598888797"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.8-GCC/LLVMCompilerRT-extract_log-v17.0.8-i686-w64-mingw32.tar.gz"
