[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "aec996e5d14e0c27e6bf24e0a952f400dfe8aca7"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "33a0c638742544c8168cfa7292ae446cea978cd0e6edbe1e2c2abed6f5240982"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-x86_64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "68c27520c816ceec4ab9cd65688d8e1c195106c5"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "d9cfae203b3cc5d8453953bbada325a53e3fa082a4ef8d4ebcf6d314b23c2beb"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-i686-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "49ce3e900adc1e49ca1e41e2d5c2f701fde376b5"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "f3e7c4472099ea08d4be6ef84104b8c62fbb2a9e0c15d5c41426d51c9e254942"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-aarch64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a53bac1cb363b7c5aa7a4bb099295d6b6a37e6e"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "617fa55e26eedb94220eac126b2d0f157d1e33554f096b411d87dc963f7d0604"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "powerpc64le"
git-tree-sha1 = "369db753febf4f658544f1cf20311b24f12381b9"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "5d868b8cf93067b17c7a252902d666a0f43628496cb010e3a7cd335ee2d33471"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "820bbefbe0773ca60b6b67c0b402ae6f817c4b14"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "f2f3bd04dea5ab64c3d70b1004cf541b0b2e95bbfc16e87e961ccf80d0f3e10b"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-x86_64-linux-musl.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "3cfbbd3e07c07252f1a3fb83ccbab9d2b920bfb7"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "db717d266d9afab8888b269ac3f38877514537d3d023742f05082faedddd38cb"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-i686-linux-musl.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "ba745b976bd9d0b0ed1e7a130bce4f40f5daa8e6"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "bc823f5168489cdca3960a9b053cb957979f573ad40f97464d8cee6103b7f037"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-aarch64-linux-musl.tar.gz"
[[LLVMCompilerRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d38abed95aa1f3f619250f1780453a1aa60be01"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "1e09de726e7d79c1566bcfbaaa1079b36fda99f06ce54d53fb28626f0d74edc0"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ecea830bef3ceb8d56734bb90b3b58bbde4281c4"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "c39d5f58a1226399dedc3b4e12ecaff138b30e5daec8f3d171733ec9696acd36"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "48bb6de231c9602c1836cfc1ea3c6ea08b1c4d75"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "8641602aa075a8de705f3f40c890b156ce3b003f33878e8018eac2304814a9ea"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "93b2a4dad059fbfaa5e6ae497aae221dfecddc3d"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "6ca9886771391bc47541818f80a3d2a862f13734280ac3716acad4824b8f53e0"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-v17.0.7-i686-w64-mingw32.tar.gz"

[[LLVMCompilerRT-build_log]]
arch = "x86_64"
git-tree-sha1 = "2b49a4ea5c58a4a9a5aae3c4dde524a195d18d96"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "9d6d9146577db0656f5d7d8da6a1930bc919d6b2c66b8ebf1d9db22f72018eb0"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "i686"
git-tree-sha1 = "e46748f5636bb76e2f2febc5ad3fd636f7c814f7"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "d0ca266218001857a070338f2ba0166229ba47b6181e15744d20faae1106cd67"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-i686-linux-gnu.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "aarch64"
git-tree-sha1 = "13c839d35f5f58461272e51407f020b005cb985c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "af1c29ab6d4b179137f0e6b19dd6777fbbb4c932a935ac3c992a96a974e4ad09"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e43042bc0d6a1135f70ac64551b5b194cb17798c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "38b9ad0812e9f8e5cb660633902117443216ee86697fa206525451a8b7aa27ab"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "27cde2f9e96431b34becaeafabb118768e3b1f3e"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "e9cd55bb9725cb0698eca3293015a8520f89164a89939197cfd51546ea8a9c3e"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "x86_64"
git-tree-sha1 = "5d54cfdd27ece37c6a311cf0fed8945a943d401c"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "fd60872941ccbcc67da3833d50514a7e044ba8612ed8c02931c6559786c7dbfd"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "i686"
git-tree-sha1 = "aa42b4da4241705336bae2ab16953382cbe288b6"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "73ad76b99d80afe99388172956d5a46c2b7513ff00b90d15d76c4218662d6de1"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-i686-linux-musl.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "aarch64"
git-tree-sha1 = "e3c3466001b2d5cdcb17a961b0e2285d7ddb0831"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "2fe3498e508a20f842ea09cc849167b8f83938a54f42333249812873eda24824"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df2eb1c5be0576ffa5dff03c2491edb7095bfa68"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "1bbe5e0be38c56b580d0368b4092b0b2fb2ad378f43993c1d0a70eddda692ecf"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd6709bf3420db2b529eae9c402d48333b4482b4"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "c378c6e285c176f1ca5c32ff0e88e3a0cdb4eb71ca656dbc3601347fa2df016e"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "x86_64"
git-tree-sha1 = "7d678ecfafa93f6eb1acbd187d3306d67d26aa88"
lazy = true
os = "windows"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "7663cc62e7c767015863a00f7de333f335f8e42e17f6c3f957683414a86cf00b"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[LLVMCompilerRT-build_log]]
arch = "i686"
git-tree-sha1 = "51ad66ddee5f20b1372ef2f842c364147ddb814b"
lazy = true
os = "windows"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "330567dde8d71be7f5aac2bc58bcb1d681430aa9923543405c5a42ade8f7789b"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-build_log-v17.0.7-i686-w64-mingw32.tar.gz"

[[LLVMCompilerRT-extract_log]]
arch = "x86_64"
git-tree-sha1 = "7a2b4cd62575df011929a55191bd1ea1384c7032"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "724cac334e5520928d993499b4b8b6ba21d53fae74f85568f9f4fe5549dd8a90"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "i686"
git-tree-sha1 = "479f94da76b78f0829400f371f3853fe9cab7c1b"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "f0452e7b0843fc21bd4193ba92b4b8d68300221527ad65cf9a05ed2e4cc51f8a"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-i686-linux-gnu.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "aarch64"
git-tree-sha1 = "2c3f68c982aebefe17915fb3b688b5373a1967b6"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "5e52daa2d5f6775b163117159d29d7105506b9bda7f7dba4c12fd556e6839755"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50fc2fc35b4f8a36f7f112ca2fece40b3d8d183b"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "d06bd423ae1ea14ea4c82fbcdfc773e91e2beb4890f98969a7c3a20c40d31a73"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "bbf91ec43267b63eb0f2cd4624c0e1048077d3e0"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "1758a2178474dcc50c85ef9897b0516516dbc4fc07bcffbd13d4e3d3c339e5bf"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "x86_64"
git-tree-sha1 = "779a409d0a73e6097d7e408cb061d880f6082689"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "bc60d04b561dfe1b0221a63c6c4d09cafdb1180a3a98b3f0eebb92e661c33cde"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "i686"
git-tree-sha1 = "d2e242fdf01a121d2843c59bc28925476d63f0ac"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "ec35b6eca90ece62f7271cd4ed408fa1338ef897f391bec22518625fa904b60f"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-i686-linux-musl.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "aarch64"
git-tree-sha1 = "203286fcef74aa613f86d1f327670899f294b530"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "5d391bf9e1d8c168edd1d37034e40d29611479f24a991de7546b8537968a0e4d"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9ffcdfe05609a7cad599626c8d16dd926c1b231f"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "c3d164fd5dd80e1f393a692b0e8958fe4304888cc927a2a75e43fb3bb21d76af"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b90ae817522d8b74613c2c86137f860fb4c961d0"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "6c58a7b84c1f4e133572e903269c667eeec5a69dc3f32cbffaad54e734f0e258"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "x86_64"
git-tree-sha1 = "819f4ebdb32e21a80558d272d1f633fbefe39d48"
lazy = true
os = "windows"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "70b9182ddb6730020367ea4b377a96b9d044c31ad05335435fe4af9f2b8ffa8a"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[LLVMCompilerRT-extract_log]]
arch = "i686"
git-tree-sha1 = "03c5830bb56526a8a9fac06b28790df5f1a52906"
lazy = true
os = "windows"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "6a19546e6a9c59403cba03aae5608ed849723c6ebe42792640219c7dce92fc02"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.7/LLVMCompilerRT-extract_log-v17.0.7-i686-w64-mingw32.tar.gz"
