[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "cb0d79ae6f1f14c98addd86655e793ac2fcb97b8"
os = "macos"
os_version = "20.0.0"

    [[LLVMCompilerRT.download]]
    sha256 = "f2fc4123e99e728673387ed0c2dfe1dab044cc3f670e25610ccd0dc996b6113b"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.9-GCCBootstrap-x86_64-linux-gnu/LLVMCompilerRT-v17.0.9-aarch64-apple-darwin20.tar.gz"

[[LLVMCompilerRT-build_log]]
arch = "aarch64"
git-tree-sha1 = "b6fadb5aeffda57e6a35852ff5874417f18edfd6"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[LLVMCompilerRT-build_log.download]]
    sha256 = "7a2314c512726b83995714dd907c4fcfda6814f388dc145db7d92fdcab8e4d52"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.9-GCCBootstrap-x86_64-linux-gnu/LLVMCompilerRT-build_log-v17.0.9-aarch64-apple-darwin20.tar.gz"

[[LLVMCompilerRT-extract_log]]
arch = "aarch64"
git-tree-sha1 = "db061c6dc9b9604507fe9565e619d39fcb42d238"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[LLVMCompilerRT-extract_log.download]]
    sha256 = "2e94069fa4411c7a4e92606cad1a84e62e9b2c4200683df32ae4d14acfa175fd"
    url = "https://github.com/staticfloat/LLVMCompilerRT_jll.jl/releases/download/v17.0.9-GCCBootstrap-x86_64-linux-gnu/LLVMCompilerRT-extract_log-v17.0.9-aarch64-apple-darwin20.tar.gz"
