# Autogenerated wrapper script for LLVMCompilerRT_jll for armv6l-linux-musleabihf
JLLWrappers.@generate_wrapper_header("LLVMCompilerRT")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
