# Autogenerated wrapper script for LLVMCompilerRT_jll for armv6l-linux-musleabihf
using XML2_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("LLVMCompilerRT")
function __init__()
    JLLWrappers.@generate_init_header(XML2_jll, Zlib_jll)
    JLLWrappers.@generate_init_footer()
end  # __init__()
