# Autogenerated wrapper script for LLVMCompilerRT_jll for armv7l-linux-gnueabihf
JLLWrappers.@generate_wrapper_header("LLVMCompilerRT")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
